pipeline:
  name: test remote
  identifier: test_remote
  projectIdentifier: Project_V2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        template:
          templateRef: account.DOE_K8S_Rolling_Deploy_Stage
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                infrastructureDefinitions: <+input>
            variables:
              - name: context_2
                type: String
                value: <+input>
              - name: serviceID
                type: String
                value: <+input>
              - name: githubBranch
                type: String
                value: <+input>
              - name: threadfixProjectName
                type: String
                value: <+input>
              - name: gateID
                type: String
                value: <+input>
              - name: policyID
                type: String
                value: <+input>
              - name: crNumber
                type: String
                value: <+input>
              - name: crOverride
                type: String
                value: <+input>
