pipeline:
  name: test remote
  identifier: test_remote
  projectIdentifier: Project_V2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test Stage Template
        identifier: Test_Stage_Template
        template:
          templateRef: StageTemplate
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          sources:
                            - identifier: _Primarytest
                              type: DockerRegistry
                              spec:
                                tag: <+input>
                      variables:
                        - name: PULSAR_SERVICE_URL
                          type: String
                          value: "<+input>.allowedValues(pulsar://dev-pulsar-proxy.dev-pulsar.svc.cluster.local:6650,pulsar://staging-pulsar-proxy.staging-pulsar.svc.cluster.local:6650,pulsar://prod-pulsar-proxy.prod-pulsar.svc.cluster.local:6650)"
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
